### ISSUE TITLE
mac下无效

### ISSUE THREAD

**Issue by neatstudio** [xuzhenjun130/Yii-t#1]
如题

**Comment by xuzhenjun130** [comment]
抱歉，没有mac，无法测试，windows测试没问题。
在phpstorm里搜索Yii-t安装插件试试吧

**Comment by neatstudio** [comment]
就是搜索了。然后无右键功能

**Comment by xuzhenjun130** [comment]
可能是phpstorm版本不兼容吧，抽空更新了代码，请重试一下吧
我依然没有测mac， windows 测试正常

**Comment by neatstudio** [comment]
新版右键可以用了（alt+3）也可以了
